version: "3"
services:
  orthanc:
    image: jodogne/orthanc-plugins
    ports:
    - 4242:4242
    - 8042:8042
    volumes:
      - ./conf/orthanc.json:/etc/orthanc/orthanc.json:ro
      - ./WorklistsDatabase:/usr/share/WorklistsDatabase
    privileged: true
