version: "3"
services:
  orthanc:
    image: jodogne/orthanc-plugins
    ports:
    - 4242:4242
    - 8042:8042
    volumes:
      - ./conf/orthanc.json:/etc/orthanc/orthanc.json:ro
      - ./WorklistsDatabase:/usr/share/WorklistsDatabase
      - ./db:/var/lib/orthanc/db/
    entrypoint: /usr/local/sbin/Orthanc /etc/orthanc/orthanc.json --verbose
    privileged: true
  ftp:
    image: stilliard/pure-ftpd:hardened
    environment:
      FTP_USER_NAME: niv
      FTP_USER_PASS: niv
      FTP_USER_HOME: /home/niv
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - ./conf/orthanc.json:/etc/orthanc/orthanc.json:ro
      - ./WorklistsDatabase:/usr/share/WorklistsDatabase
      - ./ftp:/home/niv
    privileged: true
